# Generated by Django 3.1.2 on 2020-11-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Plan',
        ),
    ]
