# Generated by Django 3.1.2 on 2020-11-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_auto_20201107_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
